### ISSUE TITLE
Javascript tests broken

### ISSUE THREAD

**Issue by duncan-bayne** [rapind/sinatra-angular-sprockets-seed#2]
When trying to run the JS tests, I get an error:

```
Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine
```

If I add Jasmine to the Gemfile and do a `bundle install`, I get a different error:

```
Unable to load jasmine config from /home/duncan/sinatra-angular-sprockets-seed/spec/javascripts/support/jasmine.yml
```

**Comment by duncan-bayne** [comment]
Looking into this now ... I'm encouraged by how quickly you merged my previous pull request :)

**Comment by rapind** [comment]
I just remember when I made this there wasn't anything around for angular +
sinatra, which is a great stack, so it'll be nice to keep it up to date.

**Comment by duncan-bayne** [comment]
Closing due to age.
